export const bossesInfo = [
  {
    bosses_position: 0,
    bosses_image: "/bosses/kaling.png",
    dashboard_position: 0,
    dashboard_image: "/bosses/kaling.png",
    meso: 750000000,
  },
  {
    bosses_position: 1,
    bosses_image: "/bosses/kalos.png",
    dashboard_position: 1,
    dashboard_image: "/bosses/kalos.png",
    meso: 750000000,
  },
  {
    bosses_position: 2,
    bosses_image: "/bosses/seren.png",
    dashboard_position: 2,
    dashboard_image: "/bosses/seren.png",
    meso: 668437500,
  },
  {
    bosses_position: 3,
    bosses_image: "/bosses/black_mage.png",
    dashboard_position: 3,
    dashboard_image: "/bosses/black_mage.png",
    meso: 2500000000,
  },
  {
    bosses_position: 4,
    bosses_image: "/bosses/darknell.png",
    dashboard_position: 4,
    dashboard_image: "/bosses/darknell.png",
    meso: 264062500,
  },
  {
    bosses_position: 5,
    bosses_image: "/bosses/verus_hilla.png",
    dashboard_position: 5,
    dashboard_image: "/bosses/verus_hilla.png",
    meso: 447600000,
  },
  {
    bosses_position: 6,
    bosses_image: "/bosses/gloom.png",
    dashboard_position: 6,
    dashboard_image: "/bosses/gloom.png",
    meso: 248062500,
  },
  {
    bosses_position: 7,
    bosses_image: "/bosses/will.png",
    dashboard_position: 7,
    dashboard_image: "/bosses/will.png",
    meso: 191275000,
  },
  {
    bosses_position: 8,
    bosses_image: "/bosses/lucid.png",
    dashboard_position: 8,
    dashboard_image: "/bosses/lucid.png",
    meso: 175562500,
  },
  {
    bosses_position: 9,
    bosses_image: "/bosses/slime.png",
    dashboard_position: 9,
    dashboard_image: "/bosses/slime.png",
    meso: 171610000,
  },
  {
    bosses_position: 10,
    bosses_image: "/bosses/damien.png",
    dashboard_position: 10,
    dashboard_image: "/bosses/damien.png",
    meso: 169000000,
  },
  {
    bosses_position: 11,
    bosses_image: "/bosses/lotus.png",
    dashboard_position: 11,
    dashboard_image: "/bosses/lotus.png",
    meso: 162562500,
  },
  {
    bosses_position: 12,
    bosses_image: "/bosses/akechi.png",
    dashboard_position: 12,
    dashboard_image: "/bosses/akechi.png",
    meso: 144000000,
  },
  {
    bosses_position: 13,
    bosses_image: "/bosses/papulatus.png",
    dashboard_position: 13,
    dashboard_image: "/bosses/papulatus.png",
    meso: 132250000,
  },
  {
    bosses_position: 14,
    bosses_image: "/bosses/magnus.png",
    dashboard_position: 14,
    dashboard_image: "/bosses/magnus.png",
    meso: 95062500,
  },
  {
    bosses_position: 15,
    bosses_image: "/bosses/vellum.png",
    dashboard_position: 15,
    dashboard_image: "/bosses/vellum.png",
    meso: 105062500,
  },
  {
    bosses_position: 16,
    bosses_image: "/bosses/von_bon.png",
    dashboard_position: 16,
    dashboard_image: "/bosses/von_bon.png",
    meso: 81000000,
  },
  {
    bosses_position: 17,
    bosses_image: "/bosses/pierre.png",
    dashboard_position: 17,
    dashboard_image: "/bosses/pierre.png",
    meso: 81000000,
  },
  {
    bosses_position: 18,
    bosses_image: "/bosses/crimson_queen.png",
    dashboard_position: 18,
    dashboard_image: "/bosses/crimson_queen.png",
    meso: 81000000,
  },
  {
    bosses_position: 19,
    bosses_image: "/bosses/princess_no.png",
    dashboard_position: 19,
    dashboard_image: "/bosses/princess_no.png",
    meso: 81000000,
  },
  {
    bosses_position: 20,
    bosses_image: "/bosses/zakum.png",
    dashboard_position: 20,
    dashboard_image: "/bosses/zakum.png",
    meso: 81000000,
  },
  {
    bosses_position: 21,
    bosses_image: "/bosses/cygnus.png",
    dashboard_position: 21,
    dashboard_image: "/bosses/cygnus.png",
    meso: 72250000,
  },
  {
    bosses_position: 22,
    bosses_image: "/bosses/pink_bean.png",
    dashboard_position: 22,
    dashboard_image: "/bosses/pink_bean.png",
    meso: 64000000,
  },
  {
    bosses_position: 23,
    bosses_image: "/bosses/hilla.png",
    dashboard_position: 23,
    dashboard_image: "/bosses/hilla.png",
    meso: 56250000,
  },
];
